services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - main
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_db:/var/lib/postgresql/data

  app:
    build: .
    container_name: app
    command: sh -c "python manage.py migrate && gunicorn SocialMedia.wsgi -b 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/code
    networks:
      - main
    depends_on:
      - postgres
    expose:
      - "8000"

  nginx:
    image: nginx:1.25.0-alpine
    container_name: nginx
    command: nginx -g "daemon off;"
    depends_on:
      - app
    restart: always
    ports:
      - "80:80"
    networks:
      - main
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  main:

volumes:
  postgres_db: